language: go
sudo: false
dist: trusty
go:
- 1.8
- 1.x
addons:
  apt:
    sources:
    - sourceline: 'ppa:masterminds/glide'
    packages:
    - glide
script:
- glide install
- go build -o minolobot_launch main.go
notifications:
  email:
    on_success: change
    on_failure: always
